# Generated by Django 3.0 on 2022-07-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO profiles_profile (
                id,
                favorite_city,
                user_id
            )
            SELECT
                id,
                favorite_city,
                user_id
            FROM
                oc_lettings_site_profile;
            SELECT setval(
                pg_get_serial_sequence('"profiles_profile"','id'),
                coalesce(max("id"), 1),
                max("id") IS NOT null) FROM "profiles_profile";
            
        """, reverse_sql="""
            INSERT INTO oc_lettings_site_profile (
                id,
                favorite_city,
                user_id
            )
            SELECT
                id,
                favorite_city,
                user_id
            FROM
                profiles_profile;
        """)
    ]
