version: '2.1'
orbs:
  python: circleci/python@2.0.3
jobs:
  env-tests:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pytest
          name: Pyest
      - run:
          command: |
            flake8
          name: Flake8
  build_docker:
    environment:
      IMAGE_NAME: litibe/p13_django
    docker:
      - image: circleci/p13_django:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest . 
  publish-latest_dockerhub:
    environment:
      IMAGE_NAME: building-on-ci
    docker:
      - image: circleci/p13_django:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  PinelineP13:
    jobs:
      - env-tests
      - build_docker:
          filters:
            branches:
              only: master
      - publish-latest_dockerhub:
          requires: 
            - build_docker
          filters:
            branches:
              only: master