version: '2.1'
orbs:
  python: circleci/python@2.0.3
jobs:
  env-tests:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pytest
          name: Pyest
      - run:
          command: |
            flake8
          name: Flake8
workflows:
  PinelineP13:
    jobs:
      - env-tests

