version: '2.1'
orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps
jobs:
  env-tests:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            pytest
          name: Pytest
      - run:
          command: |
            . venv/bin/activate
            flake8
          name: Flake8
  build_docker_and_push_to_hub:
    executor: docker-publisher
    environment:
      IMAGE_NAME: litibe/p13_django
      SECRET_KEY: $SECRET_KEY
      DEBUG: $DEBUG
      DATABASE_NAME: $DATABASE_NAME
      SENTRY_SDK: $SENTRY_SDK
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: create .env 
          command: |
            echo SENTRY_SDK=${SENTRY_SDK}
            (echo SECRET_KEY=${SECRET_KEY} 
            echo DEBUG=${DEBUG} 
            echo DATABASE_NAME=${DATABASE_NAME} 
            echo SENTRY_SDK=${SENTRY_SDK} 
            ) >> .env 
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u "$DOCKER_HUB_USER_ID" -p "$DOCKER_HUB_PASSWORD"
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
  deploy_heroku: 
    executor: heroku/default
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name : pull docker image from hub
          command: |
            docker pull litibe/p13_django:latest
      - run:
          name : Push Docker_image to Heroku
          command : |
            - heroku/install
            - run: heroku container:login
            - heroku/push-docker-image:
                process-types: web
            - heroku/release-docker-image:
                process-types: web
workflows:
  PinelineP13:
    jobs:
      - env-tests
      - build_docker_and_push_to_hub:
          requires: 
            - env-tests
          filters:
            branches:
              only: master
      - deploy_heroku:
          requires:
            - build_docker_and_push_to_hub
          filters:
            branches:
              only: master
