version: 2
orbs:
  python: circleci/python@3.10.4
jobs:
  env-and-tests:
    docker:
      - image: circleci/python:3.10.4
    steps:
     - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run flake8
          command: flake8
workflows:
  PineplineP13:
    jobs:
      - env-and-tests